#!/usr/bin/env bash
# Display information about subdomains
# Usage: ./1-world_wide_web <domain> <subdomain>

domain_info ()
{
    domain="$1"
    subdomain="$2"
    dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
	domain_info "$1" "$subdomain"
    fi
done
