#!/usr/bin/env bash
# Display information about subdomains
# Usage: ./1-world_wide_web <domain> <subdomain>

subdomains=( "www" "lb-01" "web-01" "web-02" )

domain_info () {
    subdomain=$1
    domain=$2

    dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
    domain="$1"
    for i in "${subdomains[@]}"
    do
	domain_info "$i" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    domain_info "$subdomain" "$domain"
fi
