#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page
# The redirection must be a “301 Moved Permanently”
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "301 Moved Permanently" | sudo tee -a /var/www/html/index.html
sudo sed -i '36a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
