#!/usr/bin/env bash
# configure web-02(ubuntu) to be identical to web-01

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "/server_name _;/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
sudo service nginx restart
