#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it
mysqldump -u root --password="$1" --all-databases > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
date="$day-$month-$year"
file="$date.tar.gz"
tar -czvf "$file" backup.sql
