#!/usr/bin/env bash
# Configure nginx to listen on port 80
#sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
ln -fs /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
