#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed (refer to the example)

for filename in *
do
	echo "$filename" | cut -f 2- -d '-'
done
