#!/usr/bin/env bash
# Configure nginx to run as nginx user
sudo pkill "apache2"
sudo chmod 644 /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
